### ISSUE TITLE
Blog post on building react UIs with pyodide

### ISSUE THREAD

**Issue by xhlulu** [pyodide/pyodide-blog#11]
Happy to work on a draft based on my various experiments on the subject. A summary:
1. The post would start with justifications of why python is a good choice for building UIs, then follow with an example of a simple react app, and how it can be rewritten in python via pyodide. 
2. After that, it would go over how this can be hosted on Flask or GitHub pages. 
3. Finally, an example of a [UI built in react JS](https://github.com/mui-org/material-ui/blob/master/examples/cdn/index.html) will be shown, and the same app rewritten in [proxied react](https://github.com/xhlulu/material-ui-in-pyodide/blob/main/main.py) and in a [cosmetic wrapping](https://github.com/xhlulu/pyodide-mui-modified/blob/6aee77be12c70248c239a12551a7ebd7659cad92/static/main.py#L46-L127) will be shown.

**Comment by rth** [comment]
That sounds fantastic, thanks @xhlulu !

Because your examples are relatively short, it could also be interesting to have a link to some playground at the end that includes it, to make it a bit more interactive. We have been considering it for examples in https://github.com/pyodide/pyodide/discussions/1954#discussioncomment-1680561
